/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF,Float } from "@react-three/drei";

export default function Divi(props) {
    const { nodes, materials } = useGLTF("./models/divi.glb");
    return (
        <group {...props} dispose={null} scale={6}>
          <Float floatIntensity={0.5} >
          <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve004.geometry}
        material={materials.level01}
        position={[0.002, 0.005, -0.001]}
        rotation={[1.609, 0, 0]}
      />
      </Float>
        </group>
    );
}

useGLTF.preload("/divi.glb");