/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Interface } from './interface.jsx'

import { createPortal } from "react-dom";

export default function Menu(props) {

    
    function Modal(){
    const { onSectionChange, menuOpened, setMenuOpened } = props;
    return createPortal(
        <div className={`menu-container ${menuOpened ? "open" : ""}`}>
        {/* Icône du hamburger */}

        <div className="hamburger" onClick={() => setMenuOpened(!menuOpened)}>
            <div className="bar"></div>
            <div className="bar"></div>
            <div className="bar"></div>
        </div>
    </div>
    
        
    )
}



   
    return (<>

        <Modal/>
   
      
        <div className="menu">
            <Interface />
        </div>
    </>
    )
}



